name: Rust CI

# This defines the event that triggers the workflow. 
# In this case, it runs on pushes and pull requests to the `main` branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Define a job called 'build' that runs on the latest Ubuntu environment
  test:
    runs-on: ubuntu-latest  # You can also use 'macos-latest' or 'windows-latest' if needed

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Rust (the Rust toolchain)
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable  # You can specify other versions like '1.60.0' if needed

      # Step 3: Run tests with cargo test
      - name: Run tests
        run: cargo test --verbose