name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:
  test_phaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version              

      - name: Test
        run: |
          cargo test --all          